Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.10.100"
  config.hostsupdater.aliases = ["development.local"]
  # "app" means the app folder here in atom. "/app" creates app folder in VM adds app folder in atom to VM
  config.vm.synced_folder "app", "/app"
    # "environment" means the environment folder here in atom. "/environment" creates app folder in VM adds app folder in atom to VM
  config.vm.synced_folder "environment", "/environment"
    # i want you to get everything ready on VM using the commands in provisions file
  config.vm.provision "shell", path: "environment/provision.sh"
end
